name: update data
on:
  schedule:
    # check every 10 minutes on Monday in the update window
    - cron: 3/10 14-16 * * 1
    # check every hour on Monday outside the update window
    - cron: 38 0-13,17-23 * * 1
    # check every day for the rest of the week
    - cron: 38 8 * * 0,2-6
  push:
  workflow_dispatch:
jobs:
  update-data:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v4
      - name: Cache poetry virtualenv
        uses: actions/cache@v3.0.9
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Run script
        run: poetry run python main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
